<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_tools"
 *
 * Auto generated by Extension Builder 2017-12-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'Shopware Connector',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Steffen Kroggel',
	'author_email' => 'developer@steffenkroggel.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'clearCacheOnLoad' => 0,
	'version' => '12.4.0',
	'constraints' => [
		'depends' => [
            'typo3' => '10.4.0-12.4.99',
		],
		'conflicts' => [],
		'suggests' => [],
	],
];
