routeEnhancers:
  ShopwareConnectorFull:
    type: Extbase
    extension: ShopwareConnector
    plugin: full
    routes:
      - routePath: '/shop/list/{page}'
        _controller: 'ApiRequest::list'
      - routePath: '/shop/show/{slug}/{productNumber}'
        _controller: 'ApiRequest::show'
      - routePath: '/shop/download/{productId}'
        _controller: 'ApiRequest::download'
    defaultController: 'ApiRequest::list'
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '1000'
    requirements:
      slug: '^[a-z0-9\-]+$'
      productNumber: '^[A-Za-z0-9\-_]+$'
      productId: '^[A-Za-z0-9]+$'

  ShopwareConnectorList:
    type: Extbase
    extension: ShopwareConnector
    plugin: list
    routes:
      - routePath: '/shop/list/{page}'
        _controller: 'ApiRequest::list'
    defaultController: 'ApiRequest::list'
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '1000'

  ShopwareConnectorDetail:
    type: Extbase
    extension: ShopwareConnector
    plugin: detail
    routes:
      - routePath: '/shop/show/{slug}/{productNumber}'
        _controller: 'ApiRequest::show'
    defaultController: 'ApiRequest::show'
    requirements:
      slug: '^[a-z0-9\-]+$'
      productNumber: '^[A-Za-z0-9\-_]+$'

  ShopwareConnectorDownload:
    type: Extbase
    extension: ShopwareConnector
    plugin: download
    routes:
      - routePath: '/shop/download/{productId}'
        _controller: 'ApiRequest::download'
    defaultController: 'ApiRequest::download'
    requirements:
      productId: '^[A-Za-z0-9]+$'

