services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  cache.shopwareconnector_apicalls:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['shopwareconnector_apicalls']

  Madj2k\ShopwareConnector\:
    resource: '../Classes/*'

  Madj2k\ShopwareConnector\Command\ShopwareImportCommand:
    tags:
      - name: 'console.command'
        command: 'shopware:import'
        schedulable: true
    arguments:
      $importer: '@Madj2k\ShopwareConnector\Service\ShopwareImporter'

  Madj2k\ShopwareConnector\Service\ShopwareImporter:
    arguments:
      $shopwareApiService: '@Madj2k\ShopwareConnector\Service\ShopwareApiService'

  Madj2k\ShopwareConnector\Service\ShopwareApiService:
    arguments:
      $cache: '@cache.shopwareconnector_apicalls'
      $requestFactory: '@TYPO3\CMS\Core\Http\RequestFactory'
      $registry: '@TYPO3\CMS\Core\Registry'
